### ISSUE TITLE
是否支持拆单

### ISSUE THREAD

**Issue by xieshanggao** [dromara/dax-pay#10]
在金融产品中，代扣场景会调用协议支付，很多希望能做拆分代扣或者接近实现余额代扣。举个例子假设要代扣用户1000元，卡内只有100.可以根据拆分力度进行 500元 250元 100元代扣。达到应扣尽扣原则。这个可以由dax-pay中心来支持，检查业务代码开发。把通用性功能做整合

**Comment by xxm1995** [comment]
目前是不支持的, 代扣这种业务每个渠道商都不太一样, 目前没有太好的思路做抽象, 后续有好的思路了估计会做

**Comment by xieshanggao** [comment]
我们公司实践中方案大致这样，可后续参考。  不同渠道商下面银行号卡都会有个代扣限额，一种就是按银行卡限额拆分，eg:1万的到通联通道代扣农行卡，如果限制5千，就拆2笔这样。 一种按实际代扣金额拆，当渠道商返回超限额，就按设置的比例比如4层5层这样，从大到小或从小到大送过去。      按上面说例子1000拆=》500 250 150 100 拆4分，最小金额100，总额还是1000.这样送出去还可避免多扣情况。

**Comment by xxm1995** [comment]
> 我们公司实践中方案大致这样，可后续参考。 不同渠道商下面银行号卡都会有个代扣限额，一种就是按银行卡限额拆分，eg:1万的到通联通道代扣农行卡，如果限制5千，就拆2笔这样。 一种按实际代扣金额拆，当渠道商返回超限额，就按设置的比例比如4层5层这样，从大到小或从小到大送过去。 按上面说例子1000拆=》500 250 150 100 拆4分，最小金额100，总额还是1000.这样送出去还可避免多扣情况。

我记一下, 后续做的话参考参考
