### ISSUE TITLE
是否支持微信/支付宝签约自动扣款流程

### ISSUE THREAD

**Issue by qzyu92** [dromara/dax-pay#12]
目前版本是否支持或是否后续版本有支持计划？

**Comment by xxm1995** [comment]
目前不支持, 以后有开发计划

**Comment by qzyu92** [comment]
> 目前不支持, 以后有开发计划

有大致计划或者时间表吗，比较期待这个功能

**Comment by xxm1995** [comment]
> > 目前不支持, 以后有开发计划
> 
> 有大致计划或者时间表吗，比较期待这个功能

得明年了应该，今年计划排满了
